name: Deploy to Vercel

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Set up Node.js with a compatible version
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Or you can specify '18.x' or '20.x' as needed

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run linting (optional but recommended)
      - name: Run lint
        run: npm run lint

      # Build the project
      - name: Build Project
        run: npm run build

      # Deploy to Vercel
      - name: Deploy to Vercel
        run: vercel --prod --token ${{ secrets.VERCEL_TOKEN }} --confirm
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
